baseURL = "http://example.org/"
languageCode = "en-us"
title = "Home"
theme = "kube"

[[menu.main]]
    name = "1. First installing Hugo"
    weight = -100
    url = "/posts/firstpost/"
[[menu.main]]
    name = "2. Getting the static site to work"
    weight = -100
    url = "/posts/secondpost/"
[[menu.main]]
	name = "3. Fixing the files and additional notes"
	weight = -100
	url = "/posts/thirdpost/"