baseURL = "http://example.org/"
languageCode = "en-us"
title = "Home"
theme = "kube"
Paginate = 4


[[menu.main]]
    name = "Installing Hugo on Windows"
    weight = -100
    url = "posts/firstpost/"
[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"
[[menu.main]]
    name = "Faq"
    weight = -100
url = "/faq/"